[book]
authors = ["Ian McCormack"]
language = "en"
multilingual = false
src = "src"
title = "BorrowSanitizer"

[preprocessor.rss-feed]
renderers = ["html"]

[output.html]
git-repository-url = "https://github.com/BorrowSanitizer"
site-url = "https://borrowsanitizer.com/"

[preprocessor.external-links]
after = [ "image-size" ]

[preprocessor.image-size]
command = "mdbook-image-size"

[output.html.redirect]
"/status/latest.html" = ""