[book]
authors = ["Ian McCormack"]
language = "en"
multilingual = false
src = "src"
title = "BorrowSanitizer"

[output.html]
git-repository-url = "https://github.com/BorrowSanitizer"

[preprocessor.image-size]
command = "mdbook-image-size"